services:
  db:
    image: postgres:16
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo18
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo18-db-data:/var/lib/postgresql/data

  odoo_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo18
      - DB_PASSWORD=odoo
    volumes:
      - ./customs:/customs
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo18-web-data:/var/lib/odoo

volumes:
  odoo18-web-data:
  odoo18-db-data:
